name: CI/CD pipeline
on:
  pull_request:
  push:
    branches:
      - olt

jobs:
  build:
    name: Build front-end artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checking out that code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x